website_theme: Hydra
website_name: Post to Google My Business
live_domain_url: https://posttogmb.com
website_description_text: 'The #1 WordPress plugin for managing & scheduling Google My Business posts'
social_media_share_image:
twitter_handle:
icons:
  small_bookmark_icon_image: /images/icons/favicon-16.jpg
  large_bookmark_icon_image: /images/icons/favicon-32.jpg
  small_mobile_icon_image: /images/icons/mobile-128.jpg
  large_mobile_icon_image: /images/icons/mobile-256.jpg